version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 20
    versioning-strategy: widen
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    groups:
      eslint-dependencies:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
          - "typescript-eslint"
      commitlint-dependencies:
        patterns:
          - "@commitlint/*"
      prettier-dependencies:
        patterns:
          - "prettier-*"
          - "prettier"
      testing-library-dependencies:
        patterns:
          - "@testing-library/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
