version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 20
    versioning-strategy: widen
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    groups:
      npm-eslint-dependencies:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
          - "typescript-eslint"
      npm-commitlint-dependencies:
        patterns:
          - "@commitlint/*"
      npm-prettier-dependencies:
        patterns:
          - "prettier-*"
          - "prettier"
          - "@prettier/*"
      npm-react-dependencies:
        patterns:
          - "react"
          - "react-*"
          - "@types/react"
          - "@types/react-*"
      npm-testing-library-dependencies:
        patterns:
          - "@testing-library/*"
      npm-jest-dependencies:
        patterns:
          - "jest"
          - "@types/jest"
          - "@types/jest-*"
          - "ts-jest"
          - "jest-*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
