version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 20
    versioning-strategy: widen
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    groups:
      npm-biome-dependencies:
        patterns:
          - "@biomejs/*"
      npm-commitlint-dependencies:
        patterns:
          - "@commitlint/*"
      npm-typescript-dependencies:
        patterns:
          - "typescript"
          - "ts-node"
          - "@types/node"
      npm-react-dependencies:
        patterns:
          - "react"
          - "react-*"
          - "react-dom"
          - "@types/react"
          - "@types/react-*"
      npm-testing-dependencies:
        patterns:
          - "@testing-library/*"
          - "vitest"
          - "@vitest/*"
          - "jsdom"
      npm-workspace-tooling-dependencies:
        patterns:
          - "lerna"
          - "rimraf"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "devcontainers"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
